### ISSUE TITLE
Level 18 Story is wrong

### ISSUE THREAD

**Issue by yastapova** [yastapova/WisteriaLife#1]
Correct Story:
18: Albin's Wheat Farm
You make camp at the cave, and find more supplies to sustain your journey. Continuing east, you notice that you start to encounter the Slime far more often. Luckily, at your insistence, your troops have been careful and you have not lost any to the nefarious control of this evil entity.

You continue on, and stop at Albin's Wheat Farm, one of the farms primarily responsible for sustaining the food supply of your kingdom. The farming infrastructure will have to be entirely rebuilt if your kingdom is to survive.

**Comment by yangbrian** [comment]
Resolved via Firebase.
